import Head from 'next/head';
import Link from 'next/link';
import React, { useContext, useEffect, useState } from 'react';
import { Store } from '../utils/Store';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { Menu } from '@headlessui/react';
import DropdownLink from './DropdownLink';
import { signOut, useSession } from 'next-auth/react';
import Cookies from 'js-cookie';

export default function Layout({ children, title }) {

  const { status, data: session } = useSession();
  const { state, dispatch } = useContext(Store);
  const { cart } = state;

  const [cartItemsCount, setcartItemsCount] = useState(0);
  useEffect(() => {
    setcartItemsCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0));
  }, [cart.cartItems]);

  const logoutClickHandler = () => {
    Cookies.remove('cart');
    signOut({ callbackUrl: '/login' });
    dispatch({ type: 'CART_RESET' });
  }

  return (
    <>
      <Head>
        <title>{title ? title + ' - Amazona' : 'Amazona'}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico'/>
      </Head>

      <ToastContainer position='bottom-center' limit={1} />

      <div className="flex min-h-screen flex-col justify-between ">

        {/* Header */}
        <header>
          <nav className="flex h-12 items-center px-4 justify-between shadow-md">
            <Link href="/" legacyBehavior>
              <a className="text-lg font-bold">amazona</a>
            </Link>
            
            <div>
              <Link href="/cart" legacyBehavior>
                <a className='p-2'>
                  Cart
                    {cartItemsCount > 0 && (
                      <span className="ml-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white">
                        {cartItemsCount}
                      </span>
                    )}
                </a>
              </Link>
              
              {status === 'loading' ? (
                'Loading'
              ) : session?.user ? (
                // session.user.name
                // Menu is a dropdown tab
                <Menu as='div' className='relative inlin-block'>
                  <Menu.Button className="text-blue-600">
                    {session.user.name}
                  </Menu.Button>
                  <Menu.Items className="absolute right-0 w-56 origin-top-right bg-white  shadow-lg ">
                    <Menu.Item>
                      <DropdownLink className="dropdown-link" href="/profile">
                        Profile
                      </DropdownLink>
                    </Menu.Item>
                    <Menu.Item>
                      <DropdownLink
                        className="dropdown-link"
                        href="/order-history"
                      >
                        Order History
                      </DropdownLink>
                    </Menu.Item>
                    {session.user.isAdmin && (
                      <Menu.Item>
                        <DropdownLink
                          className="dropdown-link"
                          href="/admin/dashboard"
                        >
                          Admin Dashboard
                        </DropdownLink>
                      </Menu.Item>
                    )}
                    <Menu.Item>
                      <a
                        className="dropdown-link"
                        href="#"
                        onClick={logoutClickHandler}
                      >
                        Logout
                      </a>
                    </Menu.Item>
                  </Menu.Items>
                </Menu>
              ) : (
                <Link href='/login' legacyBehavior>
                  <a className='p-2'>Login</a>
                </Link>
              )
            }

            </div>
          </nav>
        </header>

        {/* Content */}
        <main className="container m-auto mt-4 px-4">
          {children}
        </main>

        {/* Footer */}
        <footer className="flex h-10 justify-center items-center shadow-inner">
          <p>Copyright Charlie © 2022 Ecommerce website</p>
        </footer>
      </div>
    </>
  )
}
