import Head from 'next/head';
import Link from 'next/link';
import React, { useContext } from 'react';
import { Store } from '../utils/Store';

export default function Layout({ children, title }) {

  const { state } = useContext(Store);
  const { cart } = state;

  return (
    <>
      <Head>
        <title>Ecommerce website</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico'/>
      </Head>

      <div className="flex min-h-screen flex-col justify-between ">

        {/* Header */}
        <header>
          <nav className="flex h-12 items-center px-4 justify-between shadow-md">
            <Link href="/" legacyBehavior>
              <a className="text-lg font-bold">amazona</a>
            </Link>
            
            <div>
              <Link href="/cart" legacyBehavior>
                <a className='p-2'>
                  Cart
                  {cart.cartItems.length > 0 && (
                    <span className="ml-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white">
                      {cart.cartItems.reduce((a, c) => a + c.quantity, 0)}
                    </span>
                  )}
                </a>
              </Link>
              
              <Link href='/login' legacyBehavior>
                Login
              </Link>
            </div>
          </nav>
        </header>

        {/* Content */}
        <main className="container m-auto mt-4 px-4">
          {children}
        </main>

        {/* Footer */}
        <footer className="flex h-10 justify-center items-center shadow-inner">
          <p>Copyright Charlie © 2022 Ecommerce website</p>
        </footer>
      </div>
    </>
  )
}
